name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install backend dependencies
        run: cd backend/ && npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      # No need for manual dependency installation with --with-deps flag above

      - name: Create env file
        run: |
          echo "PORT=5173" > .env
          echo "DATABASE_URL=mongodb://localhost:27017/blog-test" > backend/.env

      - name: Start MongoDB
        run: |
          docker run -d -p 27017:27017 mongo:latest
          sleep 5 # Give MongoDB time to start

      - name: Run Playwright tests with debugging
        env:
          DEBUG: pw:api,pw:browser*
          NODE_ENV: test
        run: npx playwright test --timeout=60000

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30